kind: Deployment
apiVersion: apps/v1
metadata:
  name: ${project.artifactId}
  namespace: ${jkube.namespace}
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: ${project.artifactId}
  template:
    metadata:
      labels:
        deployment: ${project.artifactId}
    spec:
      containers:
        - name: ${project.artifactId}
          image: >-
            ${project.artifactId}:latest
          env:
            - name: CHAINCODE_ID
              value: >-
                ${fabric.package.id}
            - name: CORE_CHAINCODE_ID
              value: >-
                ${fabric.package.id}
            - name: CORE_CHAINCODE_ID_NAME
              value: >-
                ${fabric.package.id}
            - name: CHAINCODE_SERVER_ADDRESS
              value: '0.0.0.0:7052'
            - name: CORE_CHAINCODE_ADDRESS
              value: '0.0.0.0:7052'
            - name: CHAINCODE_TLS_DISABLED
              value: 'false'
            - name: CORE_PEER_TLS_ENABLED
              value: 'true'
            - name: CORE_TLS_CLIENT_CERT_PATH
              value: /tmp/src/maven/conf/peer/cert.crt
            - name: CORE_TLS_CLIENT_KEY_PATH
              value: /tmp/src/maven/conf/peer/priv.key
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /tmp/src/maven/conf/peer/tlsroot.crt
            - name: CORE_TLS_CLIENT_KEY_FILE
              value: >-
                /tmp/src/maven/conf/peer/cert.pem
            - name: CORE_TLS_CLIENT_CERT_FILE
              value: >-
                /tmp/src/maven/conf/peer/cert.pem
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600